---
:games:
  - torishogi
  - shogi
  - chushogi
  - tenjikushogi
  - makadaidai
:font: '/System/Library/Fonts/儷黑 Pro.ttf'
:tile: 'wood.jpg'
:colors:
  :background: none
  :border: black
  :koma: rgb(229,194,117)
  :kanji: black
  :marker: rgb(198,33,57)
  :promoted_kanji: rgb(198,33,57)

:dimensions:
  :dpi: 72.0
  :square:
    :width: 2.6
    :height: 3.2
    :units: cm
  :grid:
    :width: 0.1
    :units: cm
  :end_border:
    :width: 1.0
    :units: cm
  :side_border:
    :width: 0.9
    :units: cm
